### ISSUE TITLE
 InChIKeys in the prediction results cannot be found in public databases such as MetaNetX and PubChem

### ISSUE THREAD

**Issue by huangjingchuan12** [brsynth/RetroPathRL#19]
Hello, I encountered an issue with the data returned by RetroPathRL: the InChIKeys in the prediction results cannot be found in public databases such as MetaNetX and PubChem. I would like to switch/update the InChIKeys library in my local deployment. How should I proceed?

**Comment by huangjingchuan12** [comment]
For example, I obtained the following results using RetroPathRL for prediction：
`ILRCGYURZSFMEG-UHFFFAOYSA-N_1.json  
ILRCGYURZSFMEG-UHFFFAOYSA-N_3.json     
ILRCGYURZSFMEG-UHFFFAOYSA-N_full_tree_for_MCTS.json  
ILRCGYURZSFMEG-UHFFFAOYSA-N_iteration_30.json
ILRCGYURZSFMEG-UHFFFAOYSA-N_2.json  
ILRCGYURZSFMEG-UHFFFAOYSA-N_best.json  
ILRCGYURZSFMEG-UHFFFAOYSA-N_iteration_2.json         
ILRCGYURZSFMEG-UHFFFAOYSA-N_iteration_81.json`

However, when I use the SMILES notation of the target product from the prediction results to search in public databases, the retrieved InChIKey is ILRCGYURZSFMEG-RKQHYHRCSA-N. The InChIKey from the prediction results: ILRCGYURZSFMEG-UHFFFAOYSA-N cannot be found. It is possible that the public databases have been updated. I would like to update the InChIKeys in the software as well. How should I proceed?

**Comment by tduigou** [comment]
Hello @huangjingchuan12,

The InChIKeys are not derived from a precomputed library but are generated dynamically from the chemical structures themselves.

Given the situation you described, I would recommend trying a query using only the first layer of the InChIKey. For example, you could use `ILRCGYURZSFMEG` as the query instead of the full key `ILRCGYURZSFMEG-RKQHYHRCSA-N`.

InChIKeys are constructed by hashing layers of the InChI, which represent various structural aspects of the molecule. Molecules that share the same first layer of the InChIKey often have similar connectivity and other related features. For an very quick overview of relationships between InChIKey and InChIKey structures, you may refer to this informal introduction: [https://en.wikipedia.org/wiki/International_Chemical_Identifier#InChIKey](https://en.wikipedia.org/wiki/International_Chemical_Identifier#InChIKey).

I hope this helps!

Best regards,
